### ISSUE TITLE
Requests for Angular 2.0 final release

### ISSUE THREAD

**Issue by ukiuni** [webjars/angularjs#122]
Today https://github.com/angular/angular/releases has Angular2.0.0 and 2.0.1.
Package it to webjars.

**Comment by ukiuni** [comment]
I readed [this issue](https://github.com/webjars/angularjs/issues/119) means "use npm".
Based on this issue, I want Angular 2.0 webjars.
I think "depends on ONE build system" is better than depends on several build system.
I want to use just gradle for develop with java.

**Comment by jamesward** [comment]
You can use the NPM WebJar just like you'd use this WebJar.  Like #119 states, the lack of a zip and Angular 2's heavy usage of NPM means that we can't easily provide a Classic WebJar for it anymore.

**Comment by ukiuni** [comment]
Thank you for your answer.
Yes. You are right.
