### ISSUE TITLE
Please Release Version: 1.8.3

### ISSUE THREAD

**Issue by StanZGenchev** [webjars/angularjs#147]
AngularJS had one last bug-fix release before officially being shut down.

**Comment by jamesward** [comment]
I don't see that release at: https://code.angularjs.org/

**Comment by StanZGenchev** [comment]
Indeed there is no v1.8.3 there but they made a GitHub release:
https://github.com/angular/angular.js/releases/tag/v1.8.3

In the changelog, they say it's the last version and it's just readme updates and such but when you compare the 1.8.2 and 1.8.3 tags, you can see some other updates on dependencies such as lodash and some changes in the source.

https://github.com/angular/angular.js/blob/master/CHANGELOG.md
https://github.com/angular/angular.js/compare/v1.8.2...v1.8.3

The angular package and all extra packages such as angular-aria have also been updated in npm to version 1.8.3 (which is how I found out there was a new version).

https://www.npmjs.com/package/angular

I'm not that familiar with the internals of AngularJS, so this may be some "fake" release meant just for keeping things clean but to me, it seems like it's a genuine release. I may be wrong, though.

**Comment by jamesward** [comment]
I've deployed the NPM WebJar via https://webjars.org
```
GroupID = org.webjars.npm
ArtifactID = angular
Version = 1.8.3
```

Feel free to reopen this if that artifact doesn't work for you.
