### ISSUE TITLE
Please Release Version: 1.8.3

### ISSUE THREAD

**Issue by Horcrux7** [webjars/angularjs#149]
Please Release Version: 1.8.3

**Comment by jamesward** [comment]
I'm not seeing that release yet at: https://code.angularjs.org/

Let me know when it is there.

**Comment by Horcrux7** [comment]
If this is the source for a new version, then that's bad. I don't think this will happen after all this time of version 1.8.3. Thank you very much for your quick reply. I will look for another solution.

**Comment by nwbarrett** [comment]
I'm interested in the same 1.8.3 release, and the source code is listed on the official Github at https://github.com/angular/angular.js/releases/tag/v1.8.3

Is that a viable source of official code to include in a WebJar release?

**Comment by jamesward** [comment]
The problem with fetching it from the source tag is that it doesn't contain the built artifacts. It does seem like the NPM WebJar for Angular 1.8.3 exists and has the right stuff in it: https://www.webjars.org/listfiles/org.webjars.npm/angular/1.8.3

Will that work?

**Comment by jamesward** [comment]
We can create the Classic WebJar from the same NPM source contents but just curious, why can't you just use the existing NPM WebJar?

**Comment by nwbarrett** [comment]
Having a classic webjar would be a convenience--I have several Spring Boot projects that use parent POMs to manage dependencies and versions and the classic webjar is referenced there, so adjusting it to use the NPM webjar would require more updates.  If it's not too much of a hassle, it would be very much appreciated.  Thanks!
