### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by marceloverdijk** [webjars/angularjs#90]
Would it be a good idea to host alpha releases in webjars?

E.g. https://github.com/angular/quickstart contains alpha 14.
Currently Angular 2 is getting more attention but to work with it (e.g. downloading) is not straightforward. Perhaps webjars can add some value to this by providing Angular 2 alpha's as webjar dependency.

**Comment by jamesward** [comment]
Yeah, as long as there is a tagged release we should WebJar it.  There is already an open request (#89) that I need to process.

**Comment by jamesward** [comment]
Oh whoops.  #89 was for the 1.4 series not 2.  So I'll reopen this but we will need a tagged release to do the WebJar.  Is there one for 2.x yet?

**Comment by marceloverdijk** [comment]
Yes https://github.com/angular/angular has tags for 2.0.0-alpha.13 to 2.0.0-alpha.19.
They are also available as download here: https://github.com/angular/angular/releases

**Comment by jamesward** [comment]
I think I should just include the `modules/angular2` dir.  Does that seem right to you?

**Comment by FloWi** [comment]
Seems sufficient to me. The type-definition file (angular2.d.ts) isn't included in there. They publish it to the definitely-typed repo (https://github.com/borisyankov/DefinitelyTyped/tree/master/angular2). 

I can't think of a clever way to include angular2.d.ts in the webjar to make the typescript compiler happy. 
```typescript
/// <reference path="path/to/typings/angular2/angular2.d.ts" />
```
Do you have any practical idea to include and use it? That would make the package stand-alone in itself.

**Comment by jamesward** [comment]
Releasing this shortly.  But I can't think of a good way to include that `angular2.d.ts` file.  Maybe Angular has plans to include it in their distro.

**Comment by FloWi** [comment]
Thanks, James, for providing a release soon. I'll ask the angular-team if they can include the .d.ts in the future. I'll create a sample-project with play and angular2 next week. If you have already built one (or know of one) let me know.

**Comment by jjfraney** [comment]
I'm not an expert, but the TypeScript language does not seems to allow a d.ts file to be referenced as an uri (according to my quick glance at the spec).  The language is inflexible: it requires a file-path to .d.ts files.   So, if it were in a web jar, it would have to be extracted into the filesystem, manually or by the build tool.   See the TypeScript language spec, Section 11.1.1 (http://www.typescriptlang.org/Content/TypeScript%20Language%20Specification.pdf).   I also observe that .d.ts files are not served, with the compiler's javascript output, to the web client.  I think my build tool would work just as well pulling a versioned 'angular.d.ts' file from the DefinitelyTyped server directly for build-time use.
